### PR TITLE
don't overwrite potentially user created scripts

### LINKED ISSUE #74: editing existing aliases leads to unexpected results
homebrew-aliases seems to support editing alias files (there is the `brew alias --edit` command). But, some edits that result in otherwise working scripts can confuse the `alias` command leading to nonsensical output, useless files written to disk, and with the addition of the user deleting the symlink at `$HOMEBREW_PREFIX/bin/brew-*`, causes `brew alias` to overwrite user created alias scripts with corrupted data.

The following is shell output demonstrating all of the issues mentioned above. For the sake of brevity I didn't include the alias scripts, but they should be reproducible bit-for-bit using the `brew alias` and `sed` commands below.

I'm not saying that these exact scripts are useful, they aren't, but rather these are the minimal steps to reproduce issues I had with actual scripts I wrote.
```
~ $ # get a clean working state
~ $ rm -rf .brew-aliases/
~ $ ls /opt/homebrew/bin/brew-*
ls: /opt/homebrew/bin/brew-*: No such file or directory
~ $ # create aliases
~ $ brew alias hello='!echo hello world'
~ $ brew alias hello2='!echo hello again'
~ $ # edit aliases
# this edits the `#  alias:` comment at the top
~ $ sed -i '' 's/alias:.*$/better not edit this/' ~/.brew-aliases/hello
# this wraps the `echo` line in an `if` statement
~ $ sed -i '' 's/\(^echo.*$\)/if true; then\n  \1\nfi/' ~/.brew-aliases/hello2
~ $ # get checksums for reference
~ $ md5 .brew-aliases/*
MD5 (.brew-aliases/hello) = 5cf77855dae72c39996d8519b562cd39
MD5 (.brew-aliases/hello2) = afc0805389b434f0526959e94937370e
~ $ brew alias
brew alias # better not edit this='!echo hello world'
brew alias hello2='!if true; then'
~ $ # that output is odd, but the md5 is okay
~ $ # but there is another file?
~ $ md5 .brew-aliases/*
MD5 (.brew-aliases/__better_not_edit_this) = 17194e87812aac6f4e5be6cb8ec95d6c
MD5 (.brew-aliases/hello) = 5cf77855dae72c39996d8519b562cd39
MD5 (.brew-aliases/hello2) = afc0805389b434f0526959e94937370e
~ $ ls -1 /opt/homebrew/bin/brew-*
/opt/homebrew/bin/brew-# better not edit this
/opt/homebrew/bin/brew-hello
/opt/homebrew/bin/brew-hello2
~ $ # remove the odd file and all the symlinks
~ $ rm /opt/homebrew/bin/brew-*; rm ~/.brew-aliases/__better_not_edit_this
~ $ # run alias command again to regen symlinks
~ $ brew alias
brew alias # better not edit this='!echo hello world'
brew alias hello2='!if true; then'
~ $ md5 .brew-aliases/*
MD5 (.brew-aliases/__better_not_edit_this) = 17194e87812aac6f4e5be6cb8ec95d6c
MD5 (.brew-aliases/hello) = 5cf77855dae72c39996d8519b562cd39
MD5 (.brew-aliases/hello2) = 05e54836d8513b4d67ddc757b6734504
~ $ # ^ recreated the bad file, and now hello2 is corrupted
```

It's pretty reasonable if these types of edits aren't supported, but `brew alias` should fail a little more gracefully if it can't parse a script. I found all of this by accident, and in one case was lucky that my dotfiles are in a git repo.

### PR DESCRIPTION
**Pull request by rrotter**
- only write scripts when they don't yet exist 
- when we need the script name, trust the file name, not the script header
- fixes #74

### CODE REVIEW

File: lib/alias.rb [hunk 1]
```diff
@@ -40,6 +40,10 @@ def valid_symlink?
         false
       end
 
+      def link()
+        FileUtils.ln_sf script, symlink
```
Comment (MikeMcQuaid) [inline lib/alias.rb:44]: Just a thought: maybe we should just use `FileUtils.ln_s` here and only delete if it appropriate e.g. an existing symlink?

File: lib/aliases.rb [hunk 2]
```diff
@@ -26,7 +26,9 @@ def init
     end
 
     def add(name, command)
-      Alias.new(name, command).write
+      new_alias = Alias.new(name, command)
+      odie "alias 'brew #{name}' already exists. Sorry." if new_alias.script.exist?
```
Comment (MikeMcQuaid) [inline lib/aliases.rb:30]:
```suggestion
      odie "alias 'brew #{name}' already exists!" if new_alias.script.exist?
```

**Review by MikeMcQuaid — COMMENTED** [review]
Looks good so far! Some thoughts and CI fixes needed.

File: lib/alias.rb (hunk 1 above)
Comment (rrotter) [reply lib/alias.rb]: Agreed. Updated.

**Comment by MikeMcQuaid** [comment]
Looks good, thanks again @rrotter!
