### PR TITLE
Save in XDG_CONFIG_HOME

### LINKED ISSUE #23: Save in XDG_CONFIG_HOME
I understand the backwards compatibility issue. It'd be nice to at least be able to configure the directory. Generally I'd expect it in `.config/brew-aliases`.

### LINKED ISSUE #24: Error in unalias
I just followed the readme:

```sh
❯ brew alias status='!git status'
❯ brew alias status              
brew alias status='!git status'
❯ brew unalias status       
Error: undefined method `named' for ["status"]:Array
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-aliases/cmd/unalias.rb:22:in `unalias'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
```

### PR DESCRIPTION
**Pull request by texastoland**
Closes #23 and fixes #24 again. The command logic was inverted. I had also introduced a bug changing BASE_DIR to a Pathname.

One sticky point I noticed is it doesn't fail gracefully when symlinks are missing. The problematic use case would be restoring your dotfiles. Should there be a command to reset symlinks?

### CODE REVIEW

**Comment by texastoland** [comment]
One sticky point I noticed is it doesn't fail gracefully when symlinks are missing. The problematic use case would be restoring your dotfiles. Should there be a command to reset symlinks?

File: lib/aliases.rb [hunk 1]
```diff
@@ -2,7 +2,12 @@
 
 module Homebrew
   module Aliases
-    BASE_DIR = File.expand_path "~/.brew-aliases"
+    # Unix-Like systems store config in $HOME/.config whose location can be
+    # overriden by the XDG_CONFIG_HOME environment variable. Unfortunately
+    # Homebrew strictly filters environment variables in BuildEnvironment.
+    BASE_DIR = Pathname.new("~/.config/brew-aliases").expand_path
+    # Default to HOME to avoid creating .config in case XDG_CONFIG_HOME is set.
+    BASE_DIR = Pathname.new("~/.brew-aliases").expand_path unless BASE_DIR.directory?
```
Comment (bfontaine) [inline lib/aliases.rb:10]: Playing with `brew irb` I found that it does remove `XDG_CONFIG_HOME` from the env, but it keeps every `HOMEBREW_*` variable. We can support e.g. `HOMEBREW_ALIASES_PATH` or `HOMEBREW_ALIASES_DIR`. I think this would be better than just checking for the existence of `~/.config`, because it may break things: on my machine I have both `~/.config` and `~/.brew-aliases`.

File: lib/alias.rb [hunk 2]
```diff
@@ -6,7 +6,7 @@ class Alias
       def initialize(name, command = nil)
         @name = name.strip
 
-        command ||= if command.start_with? "!", "%"
+        command &&= if command.start_with? "!", "%"
```
Comment (bfontaine) [inline lib/alias.rb:9]: Good catch!

File: lib/aliases.rb (hunk 1 above)
Comment (texastoland) [reply lib/aliases.rb:10]: Every developer has `~/.config`. It's the default `XDG_CONFIG_HOME`. It's where the types of things go you'd version in a dotfiles repo. Precisely like this project. This line specifically checks for `~/.config/brew-aliases`. I didn't make it default because we can't check if the variable is set. In practice I doubt anyone does and it isn't worth extra configuration.

**Comment by texastoland** [comment]
> One sticky point I noticed is it doesn't fail gracefully when symlinks are missing.

Did you understand what I meant here? Try changing `~/.brew-aliases` to `~/.config/brew-aliases`. It's still valid but there's no way to fix it without manually changing the symlinks. This is a real problem for restoring them from a dotfiles repo. I think there should be some way to resync them using the directory as the source of truth.

File: lib/aliases.rb (hunk 1 above)
Comment (bfontaine) [reply lib/aliases.rb:10]: Thanks for the explanation. I thought having a `~/.config` would mess up my installation but the code does check for `~/.config/brew-aliases`, so it’s fine.

Could you just extract the code in some block or function so we have only one `BASE_DIR =` declaration?

Comment (texastoland) [reply lib/aliases.rb:10]: Do you like this?

```ruby
BASE_DIR = begin
   dir.realpath
 rescue
   Pathname.new("~/.brew-aliases").expand_path
end
```

**Comment by bfontaine** [comment]
> Did you understand what I meant here? Try changing `~/.brew-aliases` to `~/.config/brew-aliases`. It looks valid but there's no way to fix symlinks without manually overwriting them. This would be a particular problem restoring aliases from a dotfiles repo. I think there should be some command to resync from the user directory.

I missed that comment. That’s right; we can make a `brew alias --fix` command or similar that would prune dead aliases and re-create them from the correct directory.

**Comment by bfontaine** [comment]
Merged; thank you! 🎉
